### ISSUE TITLE
Déclencher le workflow 'Add issue/PR to project' à l'ouverture d'une pull request en draft

### ISSUE THREAD

**Issue by azrod** [orange-cloudavenue/workflows#14]
Actuellement, le workflow CI `Add issue/PR to project` défini dans `shared-files/github-actions/project.yml.njk` ne se déclenche pas lors de l'ouverture d'une pull request en draft. Il faudrait modifier la configuration pour que la CI s'exécute également lors de la création d'une PR en draft, afin d'assurer un suivi continu dès le début du travail sur la PR.

## Proposition de solution

Pour permettre le déclenchement de la CI à l'ouverture d'une PR en draft, il est recommandé d’ajouter le type `ready_for_review` dans la section `on.pull_request.types` du workflow, ce qui permettra également de déclencher la CI lors du passage de la PR de draft à “Ready for review”. Exemple :

```yaml
on:
  issues:
    types: [ opened, reopened, transferred, labeled ]
  pull_request:
    types: [ opened, reopened, labeled, ready_for_review ]
```

> À noter : GitHub ne déclenche pas l’événement `pull_request`/`opened` lors de l’ouverture d’une PR en mode draft, mais le déclenche lors du passage en “ready for review”. Il n’existe pas d’événement spécifique à l’ouverture d’une PR en draft. Cette modification garantit néanmoins que la CI démarre dès que possible.
