### ISSUE TITLE
Afficher un warning lors d’une CI pull request si la branche cible est main

### ISSUE THREAD

**Issue by dmicheneau** [orange-cloudavenue/workflows#15]
## Contexte
Lors de l’exécution de la CI sur une pull request, il serait utile d’ajouter un warning si la branche cible est `main`.

## Attendu
- Ajouter un mécanisme dans la CI (workflow GitHub Actions) qui affiche un message de warning dans les logs lorsque la PR cible la branche `main`.
- Le warning doit être visible mais ne doit pas entraîner l’échec de la CI.

## Objectif
Informer les contributeurs qu’une PR vers la branche `main` n’est pas recommandée sans empêcher la suite du workflow.

## Type
Amélioration

## Exemple de code (dans un job GitHub Actions) :
```yaml
[...]
- name: Check if target branch is main
  if: github.event.pull_request.base.ref == 'main'
  run: |
    echo "::warning::La branche cible de la Pull Request est main !"
  [...]
```
